### ISSUE TITLE
Firefox & Java plugin support

### ISSUE THREAD

**Issue by arktos65** [damaestro/dell-idrac-client-vagrant#2]
The current iteration installs Firefox 58, which no longer supports the Java plugin.  Because of this, a user can't access the iDRAC console because the console is a Java applet.

When trying to access the console, I receive a Java plugin error. I believe Java plugin support was discontinued with Firefox 52.

**Comment by damaestro** [comment]
https://github.com/damaestro/dell-idrac-client-vagrant/commit/93e890b5dd87da8d329601f9a78fc811a10a00e7 has a proposed fix for this. Still testing.

**Comment by damaestro** [comment]
@arktos65 please confirm this resolves the issues with older DRACs.

**Comment by arktos65** [comment]
I've confirmed that the new Vagrant box works with the older DRACs using the Java console.
