### ISSUE TITLE
vagrant up fails, cannot download image

### ISSUE THREAD

**Issue by julianbarnett** [damaestro/dell-idrac-client-vagrant#3]
dell-idrac-client-vagrant(master)~ vagrant up
Bringing machine 'dell_idrac_client' up with 'virtualbox' provider...
==> dell_idrac_client: Box 'fedora/27-cloud-base' could not be found. Attempting to find and install...
    dell_idrac_client: Box Provider: virtualbox
    dell_idrac_client: Box Version: >= 0
==> dell_idrac_client: Loading metadata for box 'fedora/27-cloud-base'
    dell_idrac_client: URL: https://vagrantcloud.com/fedora/27-cloud-base
==> dell_idrac_client: Adding box 'fedora/27-cloud-base' (v20171105) for provider: virtualbox
    dell_idrac_client: Downloading: https://vagrantcloud.com/fedora/boxes/27-cloud-base/versions/20171105/providers/virtualbox.box
    dell_idrac_client: Download redirected to host: download.fedoraproject.org
An error occurred while downloading the remote file. The error
message, if any, is reproduced below. Please fix this error and try
again.

I had to modify the Vagrant file and add the current 29-cloud-base image:

Vagrant.configure('2') do |config|
  config.vm.define :dell_idrac_client do |d|
    # base on fedora
    d.vm.box = 'fedora/29-cloud-base'
    d.vm.box_version = '29.20181024.1'

Running 'vagrant up' will then proceed

**Comment by damaestro** [comment]
Thanks for the report. I'll update the base box like you suggest after testing it a bit.

**Comment by damaestro** [comment]
@jbarnett1981 let me know if this resolves the issue for you.

**Comment by julianbarnett** [comment]
@damaestro that fixed the issue. All working now, thanks!
